{
  "openapi": "3.0.1",
  "info": {
    "title": "pensjonskalkulator API",
    "description": "Pensjonskalkulator for brukere født i 1963 eller senere",
    "version": "v1.4.0"
  },
  "externalDocs": {
    "description": "Confluence-dokumentasjon for pensjonskalkulator-backend",
    "url": "https://confluence.adeo.no/display/PEN/Pensjonskalkulator+backend"
  },
  "servers": [
    {
      "url": "https://pensjonskalkulator-backend.intern.dev.nav.no",
      "description": "Generated server url"
    }
  ],
  "paths": {
    "/api/v6/alderspensjon/simulering": {
      "post": {
        "tags": ["simulering-controller"],
        "summary": "Simuler alderspensjon",
        "description": "Lag en prognose for framtidig alderspensjon med støtte for AFP i offentlig sektor. Feltet 'epsHarInntektOver2G' brukes til å angi hvorvidt ektefelle/partner/samboer har inntekt over 2 ganger grunnbeløpet. Dersom simulering med de angitte parametre resulterer i avslag i vilkårsprøvingen, vil responsen inneholde alternative parametre som vil gi et innvilget simuleringsresultat",
        "operationId": "simulerAlderspensjonV6",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/IngressSimuleringSpecV6"
              }
            }
          },
          "required": true
        },
        "responses": {
          "503": {
            "description": "Simulering kunne ikke utføres av tekniske årsaker",
            "content": {
              "*/*": {
                "example": {
                  "timestamp": "2023-09-12T10:37:47.056+00:00",
                  "status": 503,
                  "error": "Service Unavailable",
                  "message": "En feil inntraff",
                  "path": "/api/ressurs"
                }
              }
            }
          },
          "200": {
            "description": "Simulering utført",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/SimuleringResultatV6"
                }
              }
            }
          }
        }
      }
    },
    "/api/v3/person": {
      "post": {
        "tags": ["person-controller"],
        "summary": "Hent personinformasjon",
        "description": "Henter informasjon om personen hvis person-ID er angitt enten i auth-tokenet eller i body.",
        "operationId": "personV3",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/PersonSpecV3" }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Henting av personinformasjon utført.",
            "content": {
              "*/*": { "schema": { "$ref": "#/components/schemas/PersonV3" } }
            }
          },
          "404": {
            "description": "Personen ble ikke funnet.",
            "content": {
              "*/*": { "schema": { "$ref": "#/components/schemas/PersonV3" } }
            }
          },
          "503": {
            "description": "Henting av personinformasjon kunne ikke utføres av tekniske årsaker.",
            "content": {
              "*/*": {
                "example": {
                  "timestamp": "2023-09-12T10:37:47.056+00:00",
                  "status": 503,
                  "error": "Service Unavailable",
                  "message": "En feil inntraff",
                  "path": "/api/ressurs"
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/pensjonsavtaler": {
      "post": {
        "tags": ["pensjonsavtale-controller"],
        "summary": "Hent pensjonsavtaler (versjon 2)",
        "description": "Henter pensjonsavtalene til den innloggede/angitte brukeren. I request må verdi av 'maaneder' være 0..11.",
        "operationId": "fetchAvtalerV2",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/PensjonsavtaleSpecV2" }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Henting av pensjonsavtaler utført. I respons er verdi av 'maaneder' 0..11.",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/PensjonsavtaleResultV2"
                }
              }
            }
          },
          "503": {
            "description": "Henting av pensjonsavtaler kunne ikke utføres av tekniske årsaker",
            "content": {
              "*/*": {
                "example": {
                  "timestamp": "2023-09-12T10:37:47.056+00:00",
                  "status": 503,
                  "error": "Service Unavailable",
                  "message": "En feil inntraff",
                  "path": "/api/ressurs"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/tidligste-hel-uttaksalder": {
      "post": {
        "tags": ["uttaksalder-controller"],
        "summary": "Første mulige uttaksalder ved helt uttak",
        "description": "Finn første mulige uttaksalder for innlogget bruker ved helt (100 %) uttak. Feltet 'harEps' brukes til å angi om brukeren har ektefelle/partner/samboer eller ei",
        "operationId": "finnTidligsteHelUttaksalderV1",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/IngressUttaksalderSpecForHeltUttakV1"
              }
            }
          },
          "required": true
        },
        "responses": {
          "503": {
            "description": "Søk etter uttaksalder kunne ikke utføres av tekniske årsaker",
            "content": {
              "*/*": {
                "example": {
                  "timestamp": "2023-09-12T10:37:47.056+00:00",
                  "status": 503,
                  "error": "Service Unavailable",
                  "message": "En feil inntraff",
                  "path": "/api/ressurs"
                }
              }
            }
          },
          "200": {
            "description": "Søk etter uttaksalder utført. I resultatet er verdi av 'maaneder' 0..11.",
            "content": {
              "*/*": { "schema": { "$ref": "#/components/schemas/AlderDto" } }
            }
          }
        }
      }
    },
    "/api/v1/tidligste-gradert-uttaksalder": {
      "post": {
        "tags": ["uttaksalder-controller"],
        "summary": "Første mulige uttaksalder ved gradert uttak",
        "description": "Finn første mulige uttaksalder for innlogget bruker ved gradert (20–80 %) uttak. Feltet 'harEps' brukes til å angi om brukeren har ektefelle/partner/samboer eller ei",
        "operationId": "finnTidligsteGradertUttaksalderV1",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/IngressUttaksalderSpecForGradertUttakV1"
              }
            }
          },
          "required": true
        },
        "responses": {
          "503": {
            "description": "Søk etter uttaksalder kunne ikke utføres av tekniske årsaker",
            "content": {
              "*/*": {
                "example": {
                  "timestamp": "2023-09-12T10:37:47.056+00:00",
                  "status": 503,
                  "error": "Service Unavailable",
                  "message": "En feil inntraff",
                  "path": "/api/ressurs"
                }
              }
            }
          },
          "200": {
            "description": "Søk etter uttaksalder utført. I resultatet er verdi av 'maaneder' 0..11.",
            "content": {
              "*/*": { "schema": { "$ref": "#/components/schemas/AlderDto" } }
            }
          }
        }
      }
    },
    "/api/v1/encrypt": {
      "post": {
        "tags": ["crypto-controller"],
        "summary": "Krypter tekst",
        "description": "Krypterer angitt tekst (typisk brukstilfelle er for fødselsnumre)",
        "operationId": "encrypt",
        "requestBody": {
          "content": { "application/json": { "schema": { "type": "string" } } },
          "required": true
        },
        "responses": {
          "503": {
            "description": "Kryptering kunne ikke utføres av tekniske årsaker",
            "content": {
              "*/*": {
                "example": {
                  "timestamp": "2023-09-12T10:37:47.056+00:00",
                  "status": 503,
                  "error": "Service Unavailable",
                  "message": "En feil inntraff",
                  "path": "/api/ressurs"
                }
              }
            }
          },
          "200": {
            "description": "Kryptering utført",
            "content": { "*/*": { "schema": { "type": "string" } } }
          }
        }
      }
    },
    "/api/v1/alderspensjon/anonym-simulering": {
      "post": {
        "tags": ["simulering-controller"],
        "summary": "Simuler alderspensjon anonymt (ikke innlogget)",
        "description": "Lag en prognose for framtidig alderspensjon med støtte for AFP i offentlig sektor. Feltet 'epsHarInntektOver2G' brukes til å angi hvorvidt ektefelle/partner/samboer har inntekt over 2 ganger grunnbeløpet. Dersom simulering med de angitte parametre resulterer i avslag i vilkårsprøvingen, vil responsen inneholde alternative parametre som vil gi et innvilget simuleringsresultat",
        "operationId": "simulerAnonymAlderspensjonV1",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AnonymSimuleringSpecV1"
              }
            }
          },
          "required": true
        },
        "responses": {
          "503": {
            "description": "Simulering kunne ikke utføres av tekniske årsaker",
            "content": {
              "*/*": {
                "example": {
                  "timestamp": "2023-09-12T10:37:47.056+00:00",
                  "status": 503,
                  "error": "Service Unavailable",
                  "message": "En feil inntraff",
                  "path": "/api/ressurs"
                }
              }
            }
          },
          "200": {
            "description": "Simulering utført",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/AnonymSimuleringResultV1"
                }
              }
            }
          }
        }
      }
    },
    "/api/ufoerepensjon": {
      "post": {
        "tags": ["ufoerepensjon-controller"],
        "summary": "Har løpende uføretrygd",
        "description": "Hvorvidt den innloggede brukeren har løpende uføretrygd",
        "operationId": "harUfoeretrygd",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/UfoerepensjonSpecDto" }
            }
          },
          "required": true
        },
        "responses": {
          "503": {
            "description": "Sjekking av uføretrygd kunne ikke utføres av tekniske årsaker",
            "content": {
              "*/*": {
                "example": {
                  "timestamp": "2023-09-12T10:37:47.056+00:00",
                  "status": 503,
                  "error": "Service Unavailable",
                  "message": "En feil inntraff",
                  "path": "/api/ressurs"
                }
              }
            }
          },
          "200": {
            "description": "Sjekking av uføretrygd utført",
            "content": {
              "*/*": {
                "schema": { "$ref": "#/components/schemas/UfoerepensjonDto" }
              }
            }
          }
        }
      }
    },
    "/internal/selftest": {
      "get": {
        "tags": ["self-test-controller"],
        "operationId": "selfTest",
        "responses": {
          "200": {
            "description": "OK",
            "content": { "*/*": { "schema": { "type": "string" } } }
          }
        }
      }
    },
    "/internal/env/unleash": {
      "get": {
        "tags": ["development-environment-controller"],
        "operationId": "unleashEnvironment",
        "responses": {
          "200": {
            "description": "OK",
            "content": { "*/*": { "schema": { "type": "string" } } }
          }
        }
      }
    },
    "/internal/env/mp": {
      "get": {
        "tags": ["development-environment-controller"],
        "operationId": "maskinportenEnvironment",
        "responses": {
          "200": {
            "description": "OK",
            "content": { "*/*": { "schema": { "type": "string" } } }
          }
        }
      }
    },
    "/internal/env/azure": {
      "get": {
        "tags": ["development-environment-controller"],
        "operationId": "azureEnvironment",
        "responses": {
          "200": {
            "description": "OK",
            "content": { "*/*": { "schema": { "type": "string" } } }
          }
        }
      }
    },
    "/api/v2/person": {
      "get": {
        "tags": ["person-controller"],
        "summary": "Hent personinformasjon",
        "description": "Henter personinformasjon om den innloggede brukeren.",
        "operationId": "personV2",
        "responses": {
          "200": {
            "description": "Henting av personinformasjon utført.",
            "content": {
              "*/*": { "schema": { "$ref": "#/components/schemas/PersonV2" } }
            }
          },
          "404": {
            "description": "Personen ble ikke funnet.",
            "content": {
              "*/*": { "schema": { "$ref": "#/components/schemas/PersonV2" } }
            }
          },
          "503": {
            "description": "Henting av personinformasjon kunne ikke utføres av tekniske årsaker.",
            "content": {
              "*/*": {
                "example": {
                  "timestamp": "2023-09-12T10:37:47.056+00:00",
                  "status": 503,
                  "error": "Service Unavailable",
                  "message": "En feil inntraff",
                  "path": "/api/ressurs"
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/ekskludert": {
      "get": {
        "tags": ["ekskludering-controller"],
        "summary": "Om personen er ekskludert fra å bruke kalkulatoren",
        "description": "Eksludering kan skyldes medlemskap i Apotekerforeningen",
        "operationId": "erEkskludertV2",
        "responses": {
          "200": {
            "description": "Sjekking av ekskludering utført",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/EkskluderingStatusV2"
                }
              }
            }
          },
          "503": {
            "description": "Sjekking av ekskludering kunne ikke utføres av tekniske årsaker",
            "content": {
              "*/*": {
                "example": {
                  "timestamp": "2023-09-12T10:37:47.056+00:00",
                  "status": 503,
                  "error": "Service Unavailable",
                  "message": "En feil inntraff",
                  "path": "/api/ressurs"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/vedtak/loepende-vedtak": {
      "get": {
        "tags": ["vedtak-controller"],
        "summary": "Har løpende vedtak",
        "description": "Hvorvidt den innloggede brukeren har løpende uføretrygd med uttaksgrad, alderspensjon med uttaksgrad, AFP i privat eller offentlig sektor",
        "operationId": "hentLoependeVedtakV1",
        "responses": {
          "200": {
            "description": "Henting av løpende vedtak utført",
            "content": {
              "*/*": {
                "schema": { "$ref": "#/components/schemas/LoependeVedtakV1" }
              }
            }
          },
          "503": {
            "description": "Henting av løpende vedtak kunne ikke utføres av tekniske årsaker",
            "content": {
              "*/*": {
                "example": {
                  "timestamp": "2023-09-12T10:37:47.056+00:00",
                  "status": 503,
                  "error": "Service Unavailable",
                  "message": "En feil inntraff",
                  "path": "/api/ressurs"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/ufoeregrad": {
      "get": {
        "tags": ["ufoerepensjon-controller"],
        "summary": "Hente gjeldende uføregrad",
        "description": "Hente gjeldende uføregrad fra løpende vedtak om uføretrygd om det finnes",
        "operationId": "hentUfoeregrad",
        "responses": {
          "200": {
            "description": "Henting av uføregrad utført",
            "content": {
              "*/*": {
                "schema": { "$ref": "#/components/schemas/UfoeregradDto" }
              }
            }
          },
          "503": {
            "description": "henting av uføregrad kunne ikke utføres av tekniske årsaker",
            "content": {
              "*/*": {
                "example": {
                  "timestamp": "2023-09-12T10:37:47.056+00:00",
                  "status": 503,
                  "error": "Service Unavailable",
                  "message": "En feil inntraff",
                  "path": "/api/ressurs"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/tpo-medlemskap": {
      "get": {
        "tags": ["tjenestepensjon-controller"],
        "summary": "Hent medlemskap i offentlige tjenestepensjonsordninger",
        "description": "Henter både aktive og inaktive medlemskap til brukeren i offentlige tjenestepensjonsordninger",
        "operationId": "hentMedlemskapITjenestepensjonsordninger",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/MedlemskapITjenestepensjonsordningDto"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/loepende-omstillingsstoenad-eller-gjenlevendeytelse": {
      "get": {
        "tags": ["omstillingsstoenad-og-gjenlevende-ytelse-controller"],
        "summary": "Mottar omstillingsstønad eller gjenlevende ytelse",
        "description": "Hvorvidt den innloggede brukeren mottar omstillingsstønad eller gjenlevende ytelse",
        "operationId": "mottarOmstillingsstoenadEllerGjenlevendeYtelse",
        "responses": {
          "200": {
            "description": "Henting av omstillingsstønad eller gjenlevende ytelse utført.",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/BrukerHarLoependeOmstillingsstoenadEllerGjenlevendeYtelse"
                }
              }
            }
          },
          "503": {
            "description": "Henting av omstillingsstønad eller gjenlevende ytelse kunne ikke utføres av tekniske årsaker",
            "content": {
              "*/*": {
                "example": {
                  "timestamp": "2023-09-12T10:37:47.056+00:00",
                  "status": 503,
                  "error": "Service Unavailable",
                  "message": "En feil inntraff",
                  "path": "/api/ressurs"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/land-liste": {
      "get": {
        "tags": ["land-controller"],
        "summary": "Hent land-liste",
        "description": "Henter liste over land med navn og status som avtaleland. Denne tjenesten er åpen - krever ikke autentisering.",
        "operationId": "landListe",
        "responses": {
          "503": {
            "description": "Henting av land-liste kunne ikke utføres av tekniske årsaker.",
            "content": {
              "*/*": {
                "example": {
                  "timestamp": "2023-09-12T10:37:47.056+00:00",
                  "status": 503,
                  "error": "Service Unavailable",
                  "message": "En feil inntraff",
                  "path": "/api/ressurs"
                }
              }
            }
          },
          "200": {
            "description": "Henting av land-liste utført.",
            "content": {
              "*/*": {
                "schema": {
                  "type": "array",
                  "items": { "$ref": "#/components/schemas/LandInfo" }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/ekskludert": {
      "get": {
        "tags": ["ekskludering-controller"],
        "summary": "Om personen er ekskludert fra å bruke kalkulatoren",
        "description": "Eksludering kan skyldes løpende uføretrygd, gjenlevendeytelse eller medlemskap i Apotekerforeningen",
        "operationId": "erEkskludertV1",
        "responses": {
          "200": {
            "description": "Sjekking av ekskludering utført",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/EkskluderingStatusV1"
                }
              }
            }
          },
          "503": {
            "description": "Sjekking av ekskludering kunne ikke utføres av tekniske årsaker",
            "content": {
              "*/*": {
                "example": {
                  "timestamp": "2023-09-12T10:37:47.056+00:00",
                  "status": 503,
                  "error": "Service Unavailable",
                  "message": "En feil inntraff",
                  "path": "/api/ressurs"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/crypto/public-key": {
      "get": {
        "tags": ["crypto-controller"],
        "summary": "Hent offentlig nøkkel for kryptering",
        "description": "Henter offentlig nøkkel for kryptering (f.eks. for å skjule fødselsnummer).",
        "operationId": "publicKey",
        "responses": {
          "503": {
            "description": "Henting av nøkkel kunne ikke utføres av tekniske årsaker.",
            "content": {
              "*/*": {
                "example": {
                  "timestamp": "2023-09-12T10:37:47.056+00:00",
                  "status": 503,
                  "error": "Service Unavailable",
                  "message": "En feil inntraff",
                  "path": "/api/ressurs"
                }
              }
            }
          },
          "200": {
            "description": "Henting av nøkkel utført.",
            "content": { "*/*": { "schema": { "type": "string" } } }
          }
        }
      }
    },
    "/api/v1/ansatt-id": {
      "get": {
        "tags": ["ansatt-controller"],
        "summary": "Hent ansatt-ID",
        "description": "Henter informasjon som identifiserer den innloggede ansatte.",
        "operationId": "ansattId",
        "responses": {
          "200": {
            "description": "Henting av ansatt-ID utført.",
            "content": {
              "*/*": { "schema": { "$ref": "#/components/schemas/AnsattV1" } }
            }
          },
          "503": {
            "description": "Henting av ansatt-ID kunne ikke utføres av tekniske årsaker.",
            "content": {
              "*/*": {
                "example": {
                  "timestamp": "2023-09-12T10:37:47.056+00:00",
                  "status": 503,
                  "error": "Service Unavailable",
                  "message": "En feil inntraff",
                  "path": "/api/ressurs"
                }
              }
            }
          }
        }
      }
    },
    "/api/tpo-medlemskap": {
      "get": {
        "tags": ["tjenestepensjon-controller"],
        "summary": "Har offentlig tjenestepensjonsforhold",
        "description": "Hvorvidt den innloggede brukeren har offentlig tjenestepensjonsforhold",
        "operationId": "harTjenestepensjonsforhold",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/TjenestepensjonsforholdDto"
                }
              }
            }
          }
        }
      }
    },
    "/api/status": {
      "get": {
        "tags": ["status-controller"],
        "summary": "Sjekk status",
        "description": "Hent status for applikasjonens helsetilstand",
        "operationId": "status",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": { "$ref": "#/components/schemas/ApiStatusDto" }
              }
            }
          }
        }
      }
    },
    "/api/simulator-tmu-test": {
      "get": {
        "tags": ["kalkulator-controller"],
        "summary": "Simulator TMU-test",
        "operationId": "simulatorTidligstMuligUttakTest",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": { "schema": { "$ref": "#/components/schemas/TmuResult" } }
            }
          }
        }
      }
    },
    "/api/simulator-status-test": {
      "get": {
        "tags": ["kalkulator-controller"],
        "summary": "Simulator status-test",
        "operationId": "simulatorStatusTest",
        "responses": {
          "200": {
            "description": "OK",
            "content": { "*/*": { "schema": { "type": "string" } } }
          }
        }
      }
    },
    "/api/simulator-sfb-test": {
      "get": {
        "tags": ["kalkulator-controller"],
        "summary": "Simulator simuler-folketrygdbeholdning-test",
        "operationId": "simulatorFolketrygdbeholdningTest",
        "responses": {
          "200": {
            "description": "OK",
            "content": { "*/*": { "schema": { "type": "string" } } }
          }
        }
      }
    },
    "/api/simulator-ap-test": {
      "get": {
        "tags": ["kalkulator-controller"],
        "summary": "Simulator simuler-alderspensjon-test",
        "operationId": "simulatorAlderspensjonTest",
        "responses": {
          "200": {
            "description": "OK",
            "content": { "*/*": { "schema": { "type": "string" } } }
          }
        }
      }
    },
    "/api/sak-status": {
      "get": {
        "tags": ["sak-controller"],
        "summary": "Har uføretrygd/gjenlevendeytelse",
        "description": "Hvorvidt den innloggede brukeren har løpende uføretrygd eller gjenlevendeytelse",
        "operationId": "harRelevantSak",
        "responses": {
          "503": {
            "description": "Sjekking av saker kunne ikke utføres av tekniske årsaker",
            "content": {
              "*/*": {
                "example": {
                  "timestamp": "2023-09-12T10:37:47.056+00:00",
                  "status": 503,
                  "error": "Service Unavailable",
                  "message": "En feil inntraff",
                  "path": "/api/ressurs"
                }
              }
            }
          },
          "200": {
            "description": "Sjekking av saker utført",
            "content": {
              "*/*": { "schema": { "$ref": "#/components/schemas/SakDto" } }
            }
          }
        }
      }
    },
    "/api/inntekt": {
      "get": {
        "tags": ["inntekt-controller"],
        "summary": "Siste pensjonsgivende inntekt",
        "description": "Henter den innloggede brukerens sist skattelignede pensjonsgivende inntekt",
        "operationId": "sistePensjonsgivendeInntekt",
        "responses": {
          "503": {
            "description": "Henting av inntekt kunne ikke utføres av tekniske årsaker",
            "content": {
              "*/*": {
                "example": {
                  "timestamp": "2023-09-12T10:37:47.056+00:00",
                  "status": 503,
                  "error": "Service Unavailable",
                  "message": "En feil inntraff",
                  "path": "/api/ressurs"
                }
              }
            }
          },
          "200": {
            "description": "Henting av inntekt utført.",
            "content": {
              "*/*": { "schema": { "$ref": "#/components/schemas/InntektDto" } }
            }
          }
        }
      }
    },
    "/api/grunnbeloep": {
      "get": {
        "tags": ["kalkulator-controller"],
        "summary": "Hent grunnbeløp",
        "description": "Hent grunnbeløpet i folketrygden (G) for nåværende tidspunkt",
        "operationId": "getGrunnbeloep",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": { "$ref": "#/components/schemas/Grunnbeloep" }
              }
            }
          }
        }
      }
    },
    "/api/feature/{name}": {
      "get": {
        "tags": ["feature-toggle-controller"],
        "summary": "Hvorvidt en gitt funksjonsbryter er skrudd på",
        "description": "Hent status for en gitt funksjonsbryter (hvorvidt funksjonen er skrudd på)",
        "operationId": "isEnabled",
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "required": true,
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "Sjekking av funksjonsbryter-status",
            "content": {
              "*/*": {
                "schema": { "$ref": "#/components/schemas/EnablementDto" }
              }
            }
          },
          "503": {
            "description": "Sjekking av funksjonsbryter-status kunne ikke utføres av tekniske årsaker",
            "content": {
              "*/*": {
                "example": {
                  "timestamp": "2023-09-12T10:37:47.056+00:00",
                  "status": 503,
                  "error": "Service Unavailable",
                  "message": "En feil inntraff",
                  "path": "/api/ressurs"
                }
              }
            }
          }
        }
      }
    },
    "/api/csrf": {
      "get": {
        "tags": ["csrf-controller"],
        "operationId": "csrf",
        "parameters": [
          {
            "name": "csrfToken",
            "in": "query",
            "required": true,
            "schema": { "$ref": "#/components/schemas/CsrfToken" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": { "schema": { "$ref": "#/components/schemas/CsrfToken" } }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "IngressSimuleringAlderV6": {
        "required": ["aar", "maaneder"],
        "type": "object",
        "properties": {
          "aar": { "type": "integer", "format": "int32" },
          "maaneder": { "type": "integer", "format": "int32" }
        }
      },
      "IngressSimuleringGradertUttakV6": {
        "required": ["grad", "uttaksalder"],
        "type": "object",
        "properties": {
          "grad": { "type": "integer", "format": "int32" },
          "uttaksalder": {
            "$ref": "#/components/schemas/IngressSimuleringAlderV6"
          },
          "aarligInntektVsaPensjonBeloep": {
            "type": "integer",
            "format": "int32"
          }
        }
      },
      "IngressSimuleringHeltUttakV6": {
        "required": ["uttaksalder"],
        "type": "object",
        "properties": {
          "uttaksalder": {
            "$ref": "#/components/schemas/IngressSimuleringAlderV6"
          },
          "aarligInntektVsaPensjon": {
            "$ref": "#/components/schemas/IngressSimuleringInntektV6"
          }
        }
      },
      "IngressSimuleringInntektV6": {
        "required": ["beloep", "sluttAlder"],
        "type": "object",
        "properties": {
          "beloep": { "type": "integer", "format": "int32" },
          "sluttAlder": {
            "$ref": "#/components/schemas/IngressSimuleringAlderV6"
          }
        }
      },
      "IngressSimuleringSpecV6": {
        "required": [
          "epsHarInntektOver2G",
          "foedselsdato",
          "heltUttak",
          "simuleringstype"
        ],
        "type": "object",
        "properties": {
          "simuleringstype": {
            "type": "string",
            "enum": [
              "ALDERSPENSJON",
              "ALDERSPENSJON_MED_AFP_PRIVAT",
              "ALDERSPENSJON_MED_AFP_OFFENTLIG_LIVSVARIG"
            ]
          },
          "foedselsdato": { "type": "string", "format": "date" },
          "epsHarInntektOver2G": { "type": "boolean" },
          "aarligInntektFoerUttakBeloep": {
            "type": "integer",
            "format": "int32"
          },
          "sivilstand": {
            "type": "string",
            "enum": [
              "UNKNOWN",
              "UOPPGITT",
              "UGIFT",
              "GIFT",
              "ENKE_ELLER_ENKEMANN",
              "SKILT",
              "SEPARERT",
              "REGISTRERT_PARTNER",
              "SEPARERT_PARTNER",
              "SKILT_PARTNER",
              "GJENLEVENDE_PARTNER",
              "SAMBOER"
            ]
          },
          "gradertUttak": {
            "$ref": "#/components/schemas/IngressSimuleringGradertUttakV6"
          },
          "heltUttak": {
            "$ref": "#/components/schemas/IngressSimuleringHeltUttakV6"
          },
          "utenlandsperiodeListe": {
            "type": "array",
            "items": { "$ref": "#/components/schemas/UtenlandsperiodeSpecV6" }
          }
        }
      },
      "UtenlandsperiodeSpecV6": {
        "required": ["arbeidetUtenlands", "fom", "landkode"],
        "type": "object",
        "properties": {
          "fom": { "type": "string", "format": "date" },
          "tom": { "type": "string", "format": "date" },
          "landkode": { "type": "string" },
          "arbeidetUtenlands": { "type": "boolean" }
        }
      },
      "AlderV6": {
        "required": ["aar", "maaneder"],
        "type": "object",
        "properties": {
          "aar": { "type": "integer", "format": "int32" },
          "maaneder": { "type": "integer", "format": "int32" }
        }
      },
      "AlderspensjonsberegningV6": {
        "required": ["alder", "beloep"],
        "type": "object",
        "properties": {
          "alder": { "type": "integer", "format": "int32" },
          "beloep": { "type": "integer", "format": "int32" },
          "inntektspensjonBeloep": { "type": "integer", "format": "int32" },
          "garantipensjonBeloep": { "type": "integer", "format": "int32" },
          "delingstall": { "type": "number", "format": "double" },
          "pensjonBeholdningFoerUttakBeloep": {
            "type": "integer",
            "format": "int32"
          }
        }
      },
      "AlternativV6": {
        "required": ["heltUttaksalder"],
        "type": "object",
        "properties": {
          "gradertUttaksalder": { "$ref": "#/components/schemas/AlderV6" },
          "uttaksgrad": { "type": "integer", "format": "int32" },
          "heltUttaksalder": { "$ref": "#/components/schemas/AlderV6" }
        }
      },
      "PensjonsberegningAfpOffentligV6": {
        "required": ["alder", "beloep"],
        "type": "object",
        "properties": {
          "alder": { "type": "integer", "format": "int32" },
          "beloep": { "type": "integer", "format": "int32" }
        }
      },
      "PensjonsberegningV6": {
        "required": ["alder", "beloep"],
        "type": "object",
        "properties": {
          "alder": { "type": "integer", "format": "int32" },
          "beloep": { "type": "integer", "format": "int32" }
        }
      },
      "SimuleringResultatV6": {
        "required": ["alderspensjon", "vilkaarsproeving"],
        "type": "object",
        "properties": {
          "alderspensjon": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AlderspensjonsberegningV6"
            }
          },
          "afpPrivat": {
            "type": "array",
            "items": { "$ref": "#/components/schemas/PensjonsberegningV6" }
          },
          "afpOffentlig": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PensjonsberegningAfpOffentligV6"
            }
          },
          "vilkaarsproeving": {
            "$ref": "#/components/schemas/VilkaarsproevingV6"
          },
          "harForLiteTrygdetid": { "type": "boolean" },
          "trygdetid": { "type": "integer", "format": "int32" },
          "opptjeningGrunnlagListe": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/SimulertOpptjeningGrunnlagV6"
            }
          }
        }
      },
      "SimulertOpptjeningGrunnlagV6": {
        "required": ["aar", "pensjonsgivendeInntektBeloep"],
        "type": "object",
        "properties": {
          "aar": { "type": "integer", "format": "int32" },
          "pensjonsgivendeInntektBeloep": {
            "type": "integer",
            "format": "int32"
          }
        }
      },
      "VilkaarsproevingV6": {
        "required": ["vilkaarErOppfylt"],
        "type": "object",
        "properties": {
          "vilkaarErOppfylt": { "type": "boolean" },
          "alternativ": { "$ref": "#/components/schemas/AlternativV6" }
        }
      },
      "PersonSpecV3": {
        "type": "object",
        "properties": { "pid": { "type": "string" } }
      },
      "PersonV3": {
        "required": ["foedselsdato", "navn", "sivilstand"],
        "type": "object",
        "properties": {
          "navn": { "type": "string" },
          "foedselsdato": { "type": "string", "format": "date" },
          "sivilstand": {
            "type": "string",
            "enum": [
              "UNKNOWN",
              "UOPPGITT",
              "UGIFT",
              "GIFT",
              "ENKE_ELLER_ENKEMANN",
              "SKILT",
              "SEPARERT",
              "REGISTRERT_PARTNER",
              "SEPARERT_PARTNER",
              "SKILT_PARTNER",
              "GJENLEVENDE_PARTNER"
            ]
          }
        }
      },
      "PensjonsavtaleAlderSpecV2": {
        "required": ["aar", "maaneder"],
        "type": "object",
        "properties": {
          "aar": { "type": "integer", "format": "int32" },
          "maaneder": { "type": "integer", "format": "int32" }
        }
      },
      "PensjonsavtaleInntektSpecV2": {
        "required": ["beloep"],
        "type": "object",
        "properties": {
          "beloep": { "type": "integer", "format": "int32" },
          "sluttAlder": {
            "$ref": "#/components/schemas/PensjonsavtaleAlderSpecV2"
          }
        }
      },
      "PensjonsavtaleOppholdSpecV2": {
        "required": ["fom"],
        "type": "object",
        "properties": {
          "fom": { "type": "string", "format": "date" },
          "tom": { "type": "string", "format": "date" }
        }
      },
      "PensjonsavtaleSpecV2": {
        "required": ["aarligInntektFoerUttakBeloep", "uttaksperioder"],
        "type": "object",
        "properties": {
          "aarligInntektFoerUttakBeloep": {
            "type": "integer",
            "format": "int32"
          },
          "uttaksperioder": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PensjonsavtaleUttaksperiodeSpecV2"
            }
          },
          "harAfp": { "type": "boolean" },
          "harEpsPensjon": { "type": "boolean" },
          "harEpsPensjonsgivendeInntektOver2G": { "type": "boolean" },
          "antallAarIUtlandetEtter16": { "type": "integer", "format": "int32" },
          "utenlandsperioder": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PensjonsavtaleOppholdSpecV2"
            }
          },
          "sivilstand": {
            "type": "string",
            "enum": [
              "UNKNOWN",
              "UOPPGITT",
              "UGIFT",
              "GIFT",
              "ENKE_ELLER_ENKEMANN",
              "SKILT",
              "SEPARERT",
              "REGISTRERT_PARTNER",
              "SEPARERT_PARTNER",
              "SKILT_PARTNER",
              "GJENLEVENDE_PARTNER",
              "SAMBOER"
            ]
          }
        }
      },
      "PensjonsavtaleUttaksperiodeSpecV2": {
        "required": ["grad", "startAlder"],
        "type": "object",
        "properties": {
          "startAlder": {
            "$ref": "#/components/schemas/PensjonsavtaleAlderSpecV2"
          },
          "grad": { "type": "integer", "format": "int32" },
          "aarligInntektVsaPensjon": {
            "$ref": "#/components/schemas/PensjonsavtaleInntektSpecV2"
          }
        }
      },
      "Alder": {
        "required": ["aar", "maaneder"],
        "type": "object",
        "properties": {
          "aar": { "type": "integer", "format": "int32" },
          "maaneder": { "type": "integer", "format": "int32" }
        }
      },
      "PensjonsavtaleResultV2": {
        "required": ["avtaler", "utilgjengeligeSelskap"],
        "type": "object",
        "properties": {
          "avtaler": {
            "type": "array",
            "items": { "$ref": "#/components/schemas/PensjonsavtaleV2" }
          },
          "utilgjengeligeSelskap": {
            "type": "array",
            "items": { "$ref": "#/components/schemas/SelskapV2" }
          }
        }
      },
      "PensjonsavtaleV2": {
        "required": [
          "kategori",
          "produktbetegnelse",
          "startAar",
          "utbetalingsperioder"
        ],
        "type": "object",
        "properties": {
          "produktbetegnelse": { "type": "string" },
          "kategori": {
            "type": "string",
            "enum": ["UNKNOWN", "INDIVIDUELL_ORDNING", "PRIVAT_TJENESTEPENSJON"]
          },
          "startAar": { "type": "integer", "format": "int32" },
          "sluttAar": { "type": "integer", "format": "int32" },
          "utbetalingsperioder": {
            "type": "array",
            "items": { "$ref": "#/components/schemas/UtbetalingsperiodeV2" }
          }
        }
      },
      "SelskapV2": {
        "required": ["heltUtilgjengelig", "navn"],
        "type": "object",
        "properties": {
          "navn": { "type": "string" },
          "heltUtilgjengelig": { "type": "boolean" }
        }
      },
      "UtbetalingsperiodeV2": {
        "required": ["aarligUtbetaling", "grad", "startAlder"],
        "type": "object",
        "properties": {
          "startAlder": { "$ref": "#/components/schemas/Alder" },
          "sluttAlder": { "$ref": "#/components/schemas/Alder" },
          "aarligUtbetaling": { "type": "integer", "format": "int32" },
          "grad": { "type": "integer", "format": "int32" }
        }
      },
      "IngressUttaksalderAlderV1": {
        "required": ["aar", "maaneder"],
        "type": "object",
        "properties": {
          "aar": { "type": "integer", "format": "int32" },
          "maaneder": { "type": "integer", "format": "int32" }
        }
      },
      "IngressUttaksalderInntektV1": {
        "required": ["beloep"],
        "type": "object",
        "properties": {
          "beloep": { "type": "integer", "format": "int32" },
          "sluttAlder": {
            "$ref": "#/components/schemas/IngressUttaksalderAlderV1"
          }
        }
      },
      "IngressUttaksalderSpecForHeltUttakV1": {
        "type": "object",
        "properties": {
          "simuleringstype": {
            "type": "string",
            "enum": [
              "ALDERSPENSJON",
              "ALDERSPENSJON_MED_AFP_PRIVAT",
              "ALDERSPENSJON_MED_AFP_OFFENTLIG_LIVSVARIG"
            ]
          },
          "sivilstand": {
            "type": "string",
            "enum": [
              "UNKNOWN",
              "UOPPGITT",
              "UGIFT",
              "GIFT",
              "ENKE_ELLER_ENKEMANN",
              "SKILT",
              "SEPARERT",
              "REGISTRERT_PARTNER",
              "SEPARERT_PARTNER",
              "SKILT_PARTNER",
              "GJENLEVENDE_PARTNER",
              "SAMBOER"
            ]
          },
          "harEps": { "type": "boolean" },
          "aarligInntektFoerUttakBeloep": {
            "type": "integer",
            "format": "int32"
          },
          "aarligInntektVsaPensjon": {
            "$ref": "#/components/schemas/IngressUttaksalderInntektV1"
          },
          "utenlandsperiodeListe": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/UttaksalderUtenlandsperiodeSpecV1"
            }
          }
        }
      },
      "UttaksalderUtenlandsperiodeSpecV1": {
        "required": ["arbeidetUtenlands", "fom", "landkode"],
        "type": "object",
        "properties": {
          "fom": { "type": "string", "format": "date" },
          "tom": { "type": "string", "format": "date" },
          "landkode": { "type": "string" },
          "arbeidetUtenlands": { "type": "boolean" }
        }
      },
      "AlderDto": {
        "required": ["aar", "maaneder"],
        "type": "object",
        "properties": {
          "aar": { "type": "integer", "format": "int32" },
          "maaneder": { "type": "integer", "format": "int32" }
        }
      },
      "IngressUttaksalderGradertUttakV1": {
        "required": ["grad"],
        "type": "object",
        "properties": {
          "grad": { "type": "integer", "format": "int32" },
          "aarligInntektVsaPensjonBeloep": {
            "type": "integer",
            "format": "int32"
          }
        }
      },
      "IngressUttaksalderHeltUttakV1": {
        "required": ["uttaksalder"],
        "type": "object",
        "properties": {
          "uttaksalder": {
            "$ref": "#/components/schemas/IngressUttaksalderAlderV1"
          },
          "aarligInntektVsaPensjon": {
            "$ref": "#/components/schemas/IngressUttaksalderInntektV1"
          }
        }
      },
      "IngressUttaksalderSpecForGradertUttakV1": {
        "required": ["gradertUttak", "heltUttak"],
        "type": "object",
        "properties": {
          "simuleringstype": {
            "type": "string",
            "enum": [
              "ALDERSPENSJON",
              "ALDERSPENSJON_MED_AFP_PRIVAT",
              "ALDERSPENSJON_MED_AFP_OFFENTLIG_LIVSVARIG"
            ]
          },
          "sivilstand": {
            "type": "string",
            "enum": [
              "UNKNOWN",
              "UOPPGITT",
              "UGIFT",
              "GIFT",
              "ENKE_ELLER_ENKEMANN",
              "SKILT",
              "SEPARERT",
              "REGISTRERT_PARTNER",
              "SEPARERT_PARTNER",
              "SKILT_PARTNER",
              "GJENLEVENDE_PARTNER",
              "SAMBOER"
            ]
          },
          "harEps": { "type": "boolean" },
          "aarligInntektFoerUttakBeloep": {
            "type": "integer",
            "format": "int32"
          },
          "gradertUttak": {
            "$ref": "#/components/schemas/IngressUttaksalderGradertUttakV1"
          },
          "heltUttak": {
            "$ref": "#/components/schemas/IngressUttaksalderHeltUttakV1"
          },
          "utenlandsperiodeListe": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/UttaksalderUtenlandsperiodeSpecV1"
            }
          }
        }
      },
      "AnonymSimuleringAlderV1": {
        "required": ["aar", "maaneder"],
        "type": "object",
        "properties": {
          "aar": { "type": "integer", "format": "int32" },
          "maaneder": { "type": "integer", "format": "int32" }
        }
      },
      "AnonymSimuleringGradertUttakV1": {
        "required": ["grad", "uttakAlder"],
        "type": "object",
        "properties": {
          "grad": { "type": "integer", "format": "int32" },
          "uttakAlder": {
            "$ref": "#/components/schemas/AnonymSimuleringAlderV1"
          },
          "aarligInntektVsaPensjonBeloep": {
            "type": "integer",
            "format": "int32"
          }
        }
      },
      "AnonymSimuleringHeltUttakV1": {
        "required": ["uttakAlder"],
        "type": "object",
        "properties": {
          "uttakAlder": {
            "$ref": "#/components/schemas/AnonymSimuleringAlderV1"
          },
          "aarligInntektVsaPensjon": {
            "$ref": "#/components/schemas/AnonymSimuleringInntektV1"
          }
        }
      },
      "AnonymSimuleringInntektV1": {
        "required": ["beloep"],
        "type": "object",
        "properties": {
          "beloep": { "type": "integer", "format": "int32" },
          "sluttAlder": {
            "$ref": "#/components/schemas/AnonymSimuleringAlderV1"
          }
        }
      },
      "AnonymSimuleringSpecV1": {
        "required": ["foedselAar", "heltUttak"],
        "type": "object",
        "properties": {
          "simuleringType": { "type": "string" },
          "foedselAar": { "type": "integer", "format": "int32" },
          "sivilstand": { "type": "string" },
          "epsHarInntektOver2G": { "type": "boolean" },
          "epsHarPensjon": { "type": "boolean" },
          "utenlandsAntallAar": { "type": "integer", "format": "int32" },
          "inntektOver1GAntallAar": { "type": "integer", "format": "int32" },
          "aarligInntektFoerUttakBeloep": {
            "type": "integer",
            "format": "int32"
          },
          "gradertUttak": {
            "$ref": "#/components/schemas/AnonymSimuleringGradertUttakV1"
          },
          "heltUttak": {
            "$ref": "#/components/schemas/AnonymSimuleringHeltUttakV1"
          }
        }
      },
      "AnonymAlderV1": {
        "required": ["aar", "maaneder"],
        "type": "object",
        "properties": {
          "aar": { "type": "integer", "format": "int32" },
          "maaneder": { "type": "integer", "format": "int32" }
        }
      },
      "AnonymAlternativV1": {
        "required": ["heltUttaksalder"],
        "type": "object",
        "properties": {
          "gradertUttaksalder": {
            "$ref": "#/components/schemas/AnonymAlderV1"
          },
          "uttaksgrad": { "type": "integer", "format": "int32" },
          "heltUttaksalder": { "$ref": "#/components/schemas/AnonymAlderV1" }
        }
      },
      "AnonymPensjonsberegningAfpOffentligV1": {
        "required": ["alder", "beloep"],
        "type": "object",
        "properties": {
          "alder": { "type": "integer", "format": "int32" },
          "beloep": { "type": "integer", "format": "int32" }
        }
      },
      "AnonymPensjonsberegningV1": {
        "required": ["alder", "beloep"],
        "type": "object",
        "properties": {
          "alder": { "type": "integer", "format": "int32" },
          "beloep": { "type": "integer", "format": "int32" }
        }
      },
      "AnonymSimuleringResultV1": {
        "required": ["alderspensjon", "vilkaarsproeving"],
        "type": "object",
        "properties": {
          "alderspensjon": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AnonymPensjonsberegningV1"
            }
          },
          "afpPrivat": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AnonymPensjonsberegningV1"
            }
          },
          "afpOffentlig": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AnonymPensjonsberegningAfpOffentligV1"
            }
          },
          "vilkaarsproeving": {
            "$ref": "#/components/schemas/AnonymVilkaarsproevingV1"
          }
        }
      },
      "AnonymVilkaarsproevingV1": {
        "required": ["vilkaarErOppfylt"],
        "type": "object",
        "properties": {
          "vilkaarErOppfylt": { "type": "boolean" },
          "alternativ": { "$ref": "#/components/schemas/AnonymAlternativV1" }
        }
      },
      "UfoerepensjonSpecDto": {
        "required": ["fom"],
        "type": "object",
        "properties": { "fom": { "type": "string", "format": "date" } }
      },
      "UfoerepensjonDto": {
        "required": ["harUfoerepensjon"],
        "type": "object",
        "properties": { "harUfoerepensjon": { "type": "boolean" } }
      },
      "PersonV2": {
        "required": ["foedselsdato", "navn", "sivilstand"],
        "type": "object",
        "properties": {
          "navn": { "type": "string" },
          "foedselsdato": { "type": "string", "format": "date" },
          "sivilstand": {
            "type": "string",
            "enum": [
              "UNKNOWN",
              "UOPPGITT",
              "UGIFT",
              "GIFT",
              "ENKE_ELLER_ENKEMANN",
              "SKILT",
              "SEPARERT",
              "REGISTRERT_PARTNER",
              "SEPARERT_PARTNER",
              "SKILT_PARTNER",
              "GJENLEVENDE_PARTNER"
            ]
          }
        }
      },
      "EkskluderingStatusV2": {
        "required": ["aarsak", "ekskludert"],
        "type": "object",
        "properties": {
          "ekskludert": { "type": "boolean" },
          "aarsak": { "type": "string", "enum": ["NONE", "ER_APOTEKER"] }
        }
      },
      "LoependeVedtakDetaljerV1": {
        "required": ["grad", "loepende"],
        "type": "object",
        "properties": {
          "loepende": { "type": "boolean" },
          "grad": { "type": "integer", "format": "int32" },
          "fom": { "type": "string", "format": "date" }
        }
      },
      "LoependeVedtakV1": {
        "required": [
          "afpOffentlig",
          "afpPrivat",
          "alderspensjon",
          "ufoeretrygd"
        ],
        "type": "object",
        "properties": {
          "alderspensjon": {
            "$ref": "#/components/schemas/LoependeVedtakDetaljerV1"
          },
          "ufoeretrygd": {
            "$ref": "#/components/schemas/LoependeVedtakDetaljerV1"
          },
          "afpPrivat": {
            "$ref": "#/components/schemas/LoependeVedtakDetaljerV1"
          },
          "afpOffentlig": {
            "$ref": "#/components/schemas/LoependeVedtakDetaljerV1"
          }
        }
      },
      "UfoeregradDto": {
        "required": ["ufoeregrad"],
        "type": "object",
        "properties": { "ufoeregrad": { "type": "integer", "format": "int32" } }
      },
      "MedlemskapITjenestepensjonsordningDto": {
        "required": ["tpLeverandoerListe"],
        "type": "object",
        "properties": {
          "tpLeverandoerListe": {
            "type": "array",
            "items": { "type": "string" }
          }
        }
      },
      "BrukerHarLoependeOmstillingsstoenadEllerGjenlevendeYtelse": {
        "required": ["harLoependeSak"],
        "type": "object",
        "properties": { "harLoependeSak": { "type": "boolean" } }
      },
      "LandInfo": {
        "required": ["bokmaalNavn", "engelskNavn", "landkode", "nynorskNavn"],
        "type": "object",
        "properties": {
          "landkode": { "type": "string" },
          "kravOmArbeid": { "type": "boolean" },
          "bokmaalNavn": { "type": "string" },
          "nynorskNavn": { "type": "string" },
          "engelskNavn": { "type": "string" }
        }
      },
      "EkskluderingStatusV1": {
        "required": ["aarsak", "ekskludert"],
        "type": "object",
        "properties": {
          "ekskludert": { "type": "boolean" },
          "aarsak": {
            "type": "string",
            "enum": [
              "NONE",
              "HAR_LOEPENDE_UFOERETRYGD",
              "HAR_GJENLEVENDEYTELSE",
              "ER_APOTEKER"
            ]
          }
        }
      },
      "AnsattV1": {
        "required": ["id"],
        "type": "object",
        "properties": { "id": { "type": "string" } }
      },
      "TjenestepensjonsforholdDto": {
        "required": ["harTjenestepensjonsforhold"],
        "type": "object",
        "properties": { "harTjenestepensjonsforhold": { "type": "boolean" } }
      },
      "ApiStatusDto": {
        "required": ["status"],
        "type": "object",
        "properties": { "status": { "type": "string" } }
      },
      "Tmu": {
        "required": ["tidligstMuligeUttaksdato", "uttaksgrad"],
        "type": "object",
        "properties": {
          "uttaksgrad": { "type": "integer", "format": "int32" },
          "tidligstMuligeUttaksdato": { "type": "string" }
        }
      },
      "TmuResult": {
        "required": ["tidligstMuligeUttakstidspunktListe"],
        "type": "object",
        "properties": {
          "tidligstMuligeUttakstidspunktListe": {
            "type": "array",
            "items": { "$ref": "#/components/schemas/Tmu" }
          },
          "feil": { "type": "string" }
        }
      },
      "SakDto": {
        "required": ["harUfoeretrygdEllerGjenlevendeytelse"],
        "type": "object",
        "properties": {
          "harUfoeretrygdEllerGjenlevendeytelse": { "type": "boolean" }
        }
      },
      "InntektDto": {
        "required": ["aar", "beloep"],
        "type": "object",
        "properties": {
          "beloep": { "type": "integer", "format": "int32" },
          "aar": { "type": "integer", "format": "int32" }
        }
      },
      "Grunnbeloep": {
        "required": ["value"],
        "type": "object",
        "properties": { "value": { "type": "integer", "format": "int32" } }
      },
      "EnablementDto": {
        "required": ["enabled"],
        "type": "object",
        "properties": { "enabled": { "type": "boolean" } }
      },
      "CsrfToken": {
        "type": "object",
        "properties": {
          "token": { "type": "string" },
          "headerName": { "type": "string" },
          "parameterName": { "type": "string" }
        }
      }
    }
  }
}
